### ISSUE TITLE
Incorrect scoring on summary view, part 2

### ISSUE THREAD

**Issue by mikeage** [rmick/Combobulator#16]
The issue in #5 was resolved, but I recently saw this:

![image](https://user-images.githubusercontent.com/87874/49440695-fb853400-f7cc-11e8-8485-bdc134ffe036.png)

The Hits Taken / Hits landed for player 9 (=Daddy, although you can just call me Mike ;-)) is correct, but player 1, Rivka, showed 19 instead of 9 hits landed.

The score also seems a bit absurd, and the ranking should be 1 & 2 instead of 1 & 24

This is with `v1.05 - r18.11.21`

**Comment by rmick** [comment]
Hmmm. Can't replicate it, but I have been cleaning up a fair bit of code so might have fixed it whilst tweaking something.

**Comment by mikeage** [comment]
Ok, I'll check again when the next version is out.

**Comment by rmick** [comment]
Ahhhhh.

The problem occurs when the scores are Negative numbers!

The ranking routine compares the scores of ALL 24 players, even those not in the game. Any player not in the game gets a score of 0, so a player with a negative score gets ranked lower, so ends up as Rank24.
The routine now gives players not in the game a score of -32768, to force them to the lowest ranks.

Fixed in build 18.12.21
