### ISSUE TITLE
Where are iOS builds?

### ISSUE THREAD

**Issue by dracinn** [rmick/Combobulator#31]

**Comment by rmick** [comment]
It all got too hard.

I started to look into App Store approval, but there was a lot of paperwork to fill in and no easy way to prove the app works without changing a heap of code to allow it to run without the hardware.

It 'should' compile onto iOS, but it has been at least 12-24 months since I last tried, so things may have changed. If you have Qt you can give it a go, as that allows you to direct install it onto your own devices, but I really doubt I will ever get around to it. Most people just go out and buy a <$100 Android tablet and use that.

**Comment by dracinn** [comment]
O k thanks for the response. Don't blame you as android is very accessable and easy to sideload.
